public enum TileValue
{
    ONE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE,
    EAST, SOUTH, WEST, NORTH,
    RED, GREEN, WHITE,
    PLUM_BLOSSOM, ORCHID, CHRYSANTHEMUM, BAMBOO,
    SPRING, SUMMER, AUTUMN, WINTER
}
